### PR TITLE
Issue#4 update readme

### PR DESCRIPTION
**Pull request by dangenendt**
Updated several things in readme
to have an up-to-date guideline

### CODE REVIEW

**Comment by dangenendt** [comment]
@nbrabant 
Why did you revert several things related to the upgrade? Do you have any issues with the application? Let me know
The current changes in the database-classes now are not compatible with laravel 9

**Comment by nbrabant** [comment]
Hello,
I think i was too tireed and sick yesterday, and i forget the important rule "don't rebase when you're sick" before rebasing the branch :/
The project master seems ok, i will check if migration execution are OK (for now, there are no problem on the project CI)

**Comment by dangenendt** [comment]
What should we do with this? Do i need to "repair" the branch it bring it to the "correct state"

**Comment by nbrabant** [comment]
To be clean with the history, the best strategy is recreating a new branch and cherry-pick the readme update IMO

Promise, i definitively stop rebasing ^^

**Comment by dangenendt** [comment]
Closed - will be recreated

**Pull request closed without merging**
